# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorized", "~> 0.0.0"

gem "tty-prompt", "~> 0.22.0"

gem 'tty-spinner'

gem 'terminal-table'

gem "ruby2d", "~> 0.9.4"

gem "pastel"